name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log environment variables
        run: env

      - name: Debug GitHub context (repo owner)
        run: echo "Owner - ${{ github.repository_owner }}"

      - name: Debug GitHub context (repository)
        run: echo "Repo - ${{ github.repository }}"

      - name: Debug GitHub context (ref)
        run: echo "Ref - ${{ github.ref }}"

      - name: Debug GitHub context (workflow)
        run: echo "Workflow ${{ github.workflow }}"

      - name: Debug GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Log context
        run: echo "${{ github.context }}"
      
      - name: Log repo
        run: echo "${{ github.context.repo }}"

      - name: Log repo.owner
        run: echo "${{ github.context.repo.owner }}"

      - name: Log repo.repo
        run: echo "${{ github.context.repo.repo }}"

      # **********[ irentstuff-purchase-user ]*********
      - name: Trigger irentstuff-purchase-user workflow
        if: contains(github.event.head_commit.message, 'irentstuff-purchase-user')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = github.context.repo.owner;
            await github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: '${{ github.event.repository.name }}',
              workflow_id: 'irentstuff-purchase-user.yml',
              ref: 'main'
            })