name: CI/CD Pipeline

on:
  push:
    paths:
      - "irentstuff-rental-add/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Rental Add
      - name: Install dependencies for Rental Add Function
        run: |
          cd irentstuff-rental-add
          pip install -r requirements.txt

      - name: Package Rental Add Function
        run: |
          cd irentstuff-rental-add
          zip -r ../irentstuff-rental-add.zip .

      - name: Deploy Rental Add Function to AWS Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-add --zip-file fileb://../irentstuff-rental-add.zip
  
