name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # **********[ irentstuff-purchase-user ]**********
      - name: Trigger irentstuff-purchase-user workflow
        if: contains(github.event.head_commit.message, 'irentstuff-purchase-user')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              workflow_id: 'irentstuff-purchase-user.yml',
              ref: 'main'
            })