name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Check if Lambdas need to be deployed
  orchestrate_lambda_deployments:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest
    outputs:
      deploy_purchase: ${{ steps.set_outputs.outputs.deploy_purchase }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message for irentstuff-purchase-user
        id: set_outputs
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff-purchase-user"* ]]; then
            echo "::set-output name=deploy_purchase::true"
          else
            echo "::set-output name=deploy_purchase::false"
          fi

  # Stage 2: Deploy irentstuff-purchase-user if needed
  deploy_purchase:
    name: Deploy irentstuff-purchase-user Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.check_purchase.outputs.deploy_purchase == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy irentstuff-purchase-user Lambda
        run: echo "Deploying irentstuff-purchase-user Lambda..."
        # Add your actual deployment steps here