name: CI/CD Pipeline

on:
  push:
    paths:
      - "irentstuff-rental-add/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Rental Add
      - name: Install dependencies for Rental Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        run: |
          cd irentstuff-rental-add
          pip install -r requirements.txt

      - name: Package Rental Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        run: |
          cd irentstuff-rental-add
          zip -r ../irentstuff-rental-add.zip .

      - name: Deploy Rental Add Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        uses: einaregilsson/lambda-deploy@v0.6.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: irentstuff-rental-add
          zip_file: ../irentstuff-rental-add.zip
  
