name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Check if Lambdas need to be deployed
  orchestrate_lambda_deployments:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest
    outputs:  # Insert output
      deploy_irentstuff_purchase_add: ${{ steps.set_irentstuff_purchase_add_output.outputs.deploy_irentstuff_purchase_add }}
      deploy_irentstuff_purchase_update: ${{ steps.set_irentstuff_purchase_update_output.outputs.deploy_irentstuff_purchase_update }}
      deploy_irentstuff_purchase_get: ${{ steps.set_irentstuff_purchase_get_output.outputs.deploy_irentstuff_purchase_get }}
      deploy_irentstuff_purchase_user: ${{ steps.set_irentstuff_purchase_user_output.outputs.deploy_irentstuff_purchase_user }}
      deploy_irentstuff_rental_add: ${{ steps.set_irentstuff_rental_add_output.outputs.deploy_irentstuff_rental_add }}
      deploy_irentstuff_rental_update: ${{ steps.set_irentstuff_rental_update_output.outputs.deploy_irentstuff_rental_update }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Insert check

      - name: Check commit message for irentstuff_purchase_add
        id: set_irentstuff_purchase_add_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_add"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_add::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_add::false"
          fi

      - name: Check commit message for irentstuff_purchase_update
        id: set_irentstuff_purchase_update_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_update"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_update::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_update::false"
          fi

      - name: Check commit message for irentstuff_purchase_get
        id: set_irentstuff_purchase_get_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_get"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_get::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_get::false"
          fi

      - name: Check commit message for irentstuff_purchase_user
        id: set_irentstuff_purchase_user_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_user"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_user::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_user::false"
          fi

      - name: Check commit message for irentstuff_rental_add
        id: set_irentstuff_rental_add_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_rental_add"* ]]; then
            echo "::set-output name=deploy_irentstuff_rental_add::true"
          else
            echo "::set-output name=deploy_irentstuff_rental_add::false"
          fi

      - name: Check commit message for irentstuff_rental_update
        id: set_irentstuff_rental_update_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_rental_update"* ]]; then
            echo "::set-output name=deploy_irentstuff_rental_update::true"
          else
            echo "::set-output name=deploy_irentstuff_rental_update::false"
          fi

      - name: Deployment summary
        id: deployment_summary
        run: # Insert echo
          echo "Deploy irentstuff_purchase_add - ${{ steps.set_irentstuff_purchase_add_output.outputs.deploy_irentstuff_purchase_add }}"
          echo "Deploy irentstuff_purchase_update - ${{ steps.set_irentstuff_purchase_update_output.outputs.deploy_irentstuff_purchase_update }}"
          echo "Deploy irentstuff_purchase_get - ${{ steps.set_irentstuff_purchase_get_output.outputs.deploy_irentstuff_purchase_get }}"
          echo "Deploy irentstuff_purchase_user - ${{ steps.set_irentstuff_purchase_user_output.outputs.deploy_irentstuff_purchase_user }}"
          echo "Deploy irentstuff_rental_add - ${{ steps.set_irentstuff_rental_add_output.outputs.deploy_irentstuff_rental_add }}"
          echo "Deploy irentstuff_rental_update - ${{ steps.set_irentstuff_rental_update_output.outputs.deploy_irentstuff_rental_update }}"

  # Insert stage

  # Stage 2b: Deploy irentstuff_purchase_add if triggered
  deploy_irentstuff_purchase_add:
    name: Deploy irentstuff_purchase_add Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_add == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_add
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_add Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_add
          zip -r irentstuff_purchase_add.zip .

      - name: Deploy irentstuff_purchase_add Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-add --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_add/irentstuff_purchase_add.zip

  # Stage 2c: Deploy irentstuff_purchase_update if triggered
  deploy_irentstuff_purchase_update:
    name: Deploy irentstuff_purchase_update Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_update == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_update
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_update Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_update
          zip -r irentstuff_purchase_update.zip .

      - name: Deploy irentstuff_purchase_update Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-update --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_update/irentstuff_purchase_update.zip

  # Stage 2d: Deploy irentstuff_purchase_get if triggered
  deploy_irentstuff_purchase_get:
    name: Deploy irentstuff_purchase_get Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_get == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_get
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_get Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_get
          zip -r irentstuff_purchase_get.zip .

      - name: Deploy irentstuff_purchase_get Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-get --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_get/irentstuff_purchase_get.zip

  # Stage 2e: Deploy irentstuff_purchase_user if triggered
  deploy_irentstuff_purchase_user:
    name: Deploy irentstuff_purchase_user Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_user == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_user
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_user Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_user
          zip -r irentstuff_purchase_user.zip .

      - name: Deploy irentstuff_purchase_user Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-user --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_user/irentstuff_purchase_user.zip

  # Stage 2f: Deploy irentstuff_rental_add if triggered
  deploy_irentstuff_rental_add:
    name: Deploy irentstuff_rental_add Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_rental_add == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_rental_add
          pip install -r requirements.txt

      - name: Package irentstuff_rental_add Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_rental_add
          zip -r irentstuff_rental_add.zip .

      - name: Deploy irentstuff_rental_add Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-add --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_rental_add/irentstuff_rental_add.zip

  # Stage 2g: Deploy irentstuff_rental_update if triggered
  deploy_irentstuff_rental_update:
    name: Deploy irentstuff_rental_update Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_rental_update == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_rental_update
          pip install -r requirements.txt

      - name: Package irentstuff_rental_update Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_rental_update
          zip -r irentstuff_rental_update.zip .

      - name: Deploy irentstuff_rental_update Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-update --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_rental_update/irentstuff_rental_update.zip