name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Check if Lambdas need to be deployed
  orchestrate_lambda_deployments:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest
    outputs:
      deploy_irentstuff_purchase_add: ${{ steps.set_irentstuff_purchase_add_output.outputs.deploy_irentstuff_purchase_add }}
      deploy_irentstuff_purchase_user: ${{ steps.set_irentstuff_purchase_user_output.outputs.deploy_irentstuff_purchase_user }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message for irentstuff_purchase_add
        id: set_irentstuff_purchase_add_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_add"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_add::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_add::false"
          fi

      - name: Check commit message for irentstuff_purchase_user
        id: set_irentstuff_purchase_user_output
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_user"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_user::true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_user::false"
          fi

      - name: Deployment summary
        id: deployment_summary
        run:
          echo "Deploy irentstuff_purchase_add - ${{ steps.set_irentstuff_purchase_add_output.outputs.deploy_irentstuff_purchase_add }}"
          echo "Deploy irentstuff_purchase_add - ${{ steps.set_irentstuff_purchase_user_output.outputs.deploy_irentstuff_purchase_user }}"

  # Stage 2b: Deploy irentstuff_purchase_add if triggered
  deploy_irentstuff_purchase_add:
    name: Deploy irentstuff_purchase_add Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_add == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_add
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_add Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_add
          zip -r irentstuff_purchase_add.zip .

      - name: Deploy irentstuff_purchase_add Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-add --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_add/irentstuff_purchase_add.zip

  # Stage 2e: Deploy irentstuff_purchase_user if triggered
  deploy_irentstuff_purchase_user:
    name: Deploy irentstuff_purchase_user Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_irentstuff_purchase_user == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_user
          pip install -r requirements.txt

      - name: Package irentstuff_purchase_user Lambda
        run: |
          cd $GITHUB_WORKSPACE/irentstuff_purchase_user
          zip -r irentstuff_purchase_user.zip .

      - name: Deploy irentstuff_purchase_user Lambda
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-user --zip-file fileb://$GITHUB_WORKSPACE/irentstuff_purchase_user/irentstuff_purchase_user.zip