name: CI/CD Pipeline

on:
  push:
    paths:
      - "irentstuff-rental-add/**"
      - "irentstuff-rental-update/**"
      - "irentstuff-rentals-get/**"
      - "irentstuff-rental-user/**"
      - "irentstuff-purchase-add/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # **********[ irentstuff-rental-add ]**********
      - name: Install dependencies for Rental Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-add
          pip install -r requirements.txt

      - name: Package Rental Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-add
          zip -r ../irentstuff-rental-add.zip .

      - name: Deploy Rental Add Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-add')
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-add --zip-file fileb://./irentstuff-rental-add.zip


      # **********[ irentstuff-rental-update ]**********
      - name: Install dependencies for Rental Update Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-update')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-update
          pip install -r requirements.txt

      - name: Package Rental Update Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-update')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-update
          zip -r ../irentstuff-rental-update.zip .

      - name: Deploy Rental Update Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-update')
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-update --zip-file fileb://./irentstuff-rental-update.zip


      # **********[ irentstuff-rentals-get ]**********
      - name: Install dependencies for Rentals Get Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rentals-get')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rentals-get
          pip install -r requirements.txt

      - name: Package Rentals Get Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rentals-get')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rentals-get
          zip -r ../irentstuff-rentals-get.zip .

      - name: Deploy Rentals Get Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rentals-get')
        run: |
          aws lambda update-function-code --function-name irentstuff-rentals-get --zip-file fileb://./irentstuff-rentals-get.zip


      # **********[ irentstuff-rental-user ]**********
      - name: Install dependencies for Rental User Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-user')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-user
          pip install -r requirements.txt

      - name: Package Rental User Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-user')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-rental-user
          zip -r ../irentstuff-rental-user.zip .

      - name: Deploy Rental User Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-rental-user')
        run: |
          aws lambda update-function-code --function-name irentstuff-rental-user --zip-file fileb://./irentstuff-rental-user.zip


      # **********[ irentstuff-purchase-add ]**********
      - name: Install dependencies for Purchase Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-purchase-add')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-purchase-add
          pip install -r requirements.txt

      - name: Package Purchase Add Function
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-purchase-add')
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-purchase-add
          zip -r ../irentstuff-purchase-add.zip .

      - name: Deploy Purchase Add Function to AWS Lambda
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'irentstuff-purchase-add')
        run: |
          aws lambda update-function-code --function-name irentstuff-purchase-add --zip-file fileb://./irentstuff-purchase-add.zip


      # Purchase Update


      # Purchase Get


      # Purchase User