name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Check if Lambdas need to be deployed
  orchestrate_lambda_deployments:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest
    outputs:
      deploy_purchase: ${{ steps.set_outputs.outputs.deploy_irentstuff_purchase_user }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message for irentstuff_purchase_user
        id: set_outputs
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_user"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_user::true"
            echo "deploy_irentstuff_purchase_user: true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_user::false"
            echo "deploy_irentstuff_purchase_user: false"
          fi

  # Stage 2: Deploy irentstuff_purchase_user if needed
  deploy_irentstuff_purchase_user:
    name: Deploy irentstuff_purchase_user Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_purchase == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/irentstuff-purchase-user
          pip install -r requirements.txt

      - name: Package and deploy Lambda
        run: |
          zip -r ../irentstuff-purchase-user.zip .
          aws lambda update-function-code --function-name irentstuff-purchase-user --zip-file fileb://../irentstuff-purchase-user.zip