name: Lambda Deployment Orchestrator

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Check if Lambdas need to be deployed
  orchestrate_lambda_deployments:
    name: Orchestrate Lambda deployments
    runs-on: ubuntu-latest
    outputs:
      deploy_purchase: ${{ steps.set_outputs.outputs.deploy_irentstuff_purchase_user }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message for irentstuff_purchase_user
        id: set_outputs
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"deploy irentstuff_purchase_user"* ]]; then
            echo "::set-output name=deploy_irentstuff_purchase_user::true"
            echo "deploy_irentstuff_purchase_user: true"
          else
            echo "::set-output name=deploy_irentstuff_purchase_user::false"
            echo "deploy_irentstuff_purchase_user: false"
          fi

  # Stage 2: Deploy irentstuff_purchase_user if needed
  deploy_irentstuff_purchase_user:
    name: Deploy irentstuff_purchase_user Lambda
    runs-on: ubuntu-latest
    needs: orchestrate_lambda_deployments
    if: needs.orchestrate_lambda_deployments.outputs.deploy_purchase == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy irentstuff_purchase_user Lambda
        run: echo "Deploying irentstuff_purchase_user Lambda..."
        # Add your deployment steps here